#' Write Gene covariate file to use as Gene Set for GSA. This function is a dependency of MAGMA_GSA.r
#'
#' \code{write_gene_covarfile} Writes a covariate file containing entrez gene ids of up or downregulated genes.
#'
#' @param geneset geneset a list of up or downregulated genes, obtained using MAGMA_GSA.r
#' @param varname varname Geneset name, generated by MAGMA_GSA.r: UR/DR_analysistype_species.
#' @param filename Genecovar filename, generated by MAGMA_GSA.r: GeneCovar_DR/UR_analysistype_species.
#'
#' @return Genecovar file containing the entrez ids of the n up or downregulated genes obtained using MAGMA_GSA function
#'
write_gene_covarfile <- function(geneset,varname,filename){
	geneset_entrez = MAGMA.Celltyping::all_hgnc_wtEntrez[MAGMA.Celltyping::all_hgnc_wtEntrez$hgnc_symbol %in% geneset,]$entrezgene
	if(length(geneset_entrez)/length(geneset)<0.4){stop("Less than 40% of genes in the geneset have valid entrez ids. Check species has been specidied correctly")}
	printf("%s covar file contains %s out of %s genes in the geneset. %s%% of the HGNC ids have been mapped to etrez ids. \n",filename,length(geneset_entrez),length(geneset),length(geneset_entrez)/length(geneset)*100)
	rows_geneset_entrez <- paste(c(varname,geneset_entrez),collapse=" ")
	utils::write.table(rows_geneset_entrez,file=filename,quote=FALSE,row.names=FALSE,sep="\t",col.names=FALSE)
}
